num1=input("Enter your number1\n")
print(type(num1))
num1=int(num1)
print(type(num1))
num2=input("Enter your number2\n")
num2=int(num2)
print(num1+num2)
print(num1-num2)
print(num1*num2)
print(num1/num2)